# Generated by Django 5.2.1 on 2025-06-14 08:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('insurance_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_number', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_history', models.TextField(blank=True, help_text='Brief medical history', null=True)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies', null=True)),
                ('current_medications', models.TextField(blank=True, help_text='Current medications', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients',
                'indexes': [models.Index(fields=['user'], name='patients_user_id_fdab75_idx'), models.Index(fields=['date_of_birth'], name='patients_date_of_24544d_idx'), models.Index(fields=['insurance_provider'], name='patients_insuran_8887c5_idx')],
            },
        ),
    ]
